#if !canImport(ObjectiveC)
import XCTest

extension CalculationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CalculationsTests = [
        ("testFromFrequency", testFromFrequency),
        ("testOffset", testOffset),
        ("testToFrequency", testToFrequency),
    ]
}

extension ConvertionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConvertionTests = [
        ("testNoteFromPitchFlat", testNoteFromPitchFlat),
        ("testNoteFromPitchNatural", testNoteFromPitchNatural),
        ("testNoteFromPitchSharp", testNoteFromPitchSharp),
    ]
}

extension NoteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NoteTests = [
        ("testName", testName),
        ("testNote", testNote),
        ("testNoteDescription", testNoteDescription),
        ("testPitch", testPitch),
        ("testPitchDescription", testPitchDescription),
    ]
}

extension PitchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PitchTests = [
        ("testDescription", testDescription),
        ("testFromNotePitch", testFromNotePitch),
        ("testPitch", testPitch),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CalculationsTests.__allTests__CalculationsTests),
        testCase(ConvertionTests.__allTests__ConvertionTests),
        testCase(NoteTests.__allTests__NoteTests),
        testCase(PitchTests.__allTests__PitchTests),
    ]
}
#endif
