#if !canImport(ObjectiveC)
import XCTest

extension NoteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NoteTests = [
        ("testName", testName),
        ("testNote", testNote),
        ("testNoteDescription", testNoteDescription),
        ("testPitch", testPitch),
        ("testPitchDescription", testPitchDescription),
    ]
}

extension OctaveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OctaveTests = [
        ("testOctave", testOctave),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NoteTests.__allTests__NoteTests),
        testCase(OctaveTests.__allTests__OctaveTests),
    ]
}
#endif
